import image1 from "../../images/d1.png";
import image2 from "../../images/d2.png";
import image3 from "../../images/d3.png";
import image4 from "../../images/d4.png";

const data = [
  {
    id: 1,
    img: image1,
    title: '"“Just love it”"',
    desc: "I love how user-friendly this app is! It's so easy to add events and set reminders, and it's made my life so much more organized.",
    userName: "Adam Moore",
    designation: "Head of marketing",
  },
  {
    id: 2,
    img: image2,
    title: '"“The best time manager app”"',
    desc: "This calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule.",
    userName: "Michel O Neil",
    designation: "CEO of RoastingOS",
  },
  {
    id: 3,
    img: image3,
    title: '"“Better than the rest”"',
    desc: "I've tried a lot of calendar apps, but this one is by far the best! It's so intuitive and customizable, and it has all the features I need. Game changer!",
    userName: "Kyle Conord",
    designation: "CEO of RoastingOS",
  },
//   {
//     id: 4,
//     img: image4,
//     title: '"“No more forgotten appointments”"',
//     desc: "This app is so simple yet so powerful! I love how I can easily add events and see my entire schedule at a glance.",
//     userName: "Annie Devy",
//     designation: "Product design at Lambda",
//   },
//   {
//     id: 5,
//     img: image1,
//     title: '"“Just love it”"',
//     desc: "I love how user-friendly this app is! It's so easy to add events and set reminders, and it's made my life so much more organized.",
//     userName: "Adam Moore",
//     designation: "Head of marketing",
//   },
//   {
//     id: 6,
//     img: image2,
//     title: '"“The best time manager app”"',
//     desc: "This calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule.",
//     userName: "Michel O Neil",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 7,
//     img: image3,
//     title: '"“Better than the rest”"',
//     desc: "I've tried a lot of calendar apps, but this one is by far the best! It's so intuitive and customizable, and it has all the features I need. Game changer!",
//     userName: "Kyle Conord",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 8,
//     img: image4,
//     title: '"“No more forgotten appointments”"',
//     desc: "This app is so simple yet so powerful! I love how I can easily add events and see my entire schedule at a glance.",
//     userName: "Annie Devy",
//     designation: "Product design at Lambda",
//   },
//   {
//     id: 9,
//     img: image1,
//     title: '"“Just love it”"',
//     desc: "I love how user-friendly this app is! It's so easy to add events and set reminders, and it's made my life so much more organized.",
//     userName: "Adam Moore",
//     designation: "Head of marketing",
//   },
//   {
//     id: 10,
//     img: image2,
//     title: '"“The best time manager app”"',
//     desc: "This calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule.",
//     userName: "Michel O Neil",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 11,
//     img: image3,
//     title: '"“Better than the rest”"',
//     desc: "I've tried a lot of calendar apps, but this one is by far the best! It's so intuitive and customizable, and it has all the features I need. Game changer!",
//     userName: "Kyle Conord",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 12,
//     img: image4,
//     title: '"“No more forgotten appointments”"',
//     desc: "This app is so simple yet so powerful! I love how I can easily add events and see my entire schedule at a glance.",
//     userName: "Annie Devy",
//     designation: "Product design at Lambda",
//   },
//   {
//     id: 13,
//     img: image1,
//     title: '"“Just love it”"',
//     desc: "I love how user-friendly this app is! It's so easy to add events and set reminders, and it's made my life so much more organized.",
//     userName: "Adam Moore",
//     designation: "Head of marketing",
//   },
//   {
//     id: 14,
//     img: image2,
//     title: '"“The best time manager app”"',
//     desc: "This calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule.",
//     userName: "Michel O Neil",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 15,
//     img: image3,
//     title: '"“Better than the rest”"',
//     desc: "I've tried a lot of calendar apps, but this one is by far the best! It's so intuitive and customizable, and it has all the features I need. Game changer!",
//     userName: "Kyle Conord",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 16,
//     img: image4,
//     title: '"“No more forgotten appointments”"',
//     desc: "This app is so simple yet so powerful! I love how I can easily add events and see my entire schedule at a glance.",
//     userName: "Annie Devy",
//     designation: "Product design at Lambda",
//   },
//   {
//     id: 17,
//     img: image1,
//     title: '"“Just love it”"',
//     desc: "I love how user-friendly this app is! It's so easy to add events and set reminders, and it's made my life so much more organized.",
//     userName: "Adam Moore",
//     designation: "Head of marketing",
//   },
//   {
//     id: 18,
//     img: image2,
//     title: '"“The best time manager app”"',
//     desc: "This calendar app has been a lifesaver! I used to forget important events, but now I'm always on top of my schedule.",
//     userName: "Michel O Neil",
//     designation: "CEO of RoastingOS",
//   },
//   {
//     id: 19,
//     img: image3,
//     title: '"“Better than the rest”"',
//     desc: "I've tried a lot of calendar apps, but this one is by far the best! It's so intuitive and customizable, and it has all the features I need. Game changer!",
//     userName: "Kyle Conord",
//     designation: "CEO of RoastingOS",
//   },
];

export default data;
